### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by bitemyapp** [Gabriel439/post-rfc#11]
I'd rate this best in class. We can do Erlang-style single machine concurrency, JVM-style, have the best STM implementation, have MVars, cheapest green threads, OS threads and CPU pinning are available if needed, [LVars](http://hackage.haskell.org/package/lvish) etc. 

Also see: https://news.ycombinator.com/item?id=10071905

I have a hard time knowing why this is anything other than best-in-class unless concurrency implicitly includes "distributed systems", which I don't believe it does.

[See, even you were thinking it](https://www.reddit.com/r/haskell/comments/3haulk/state_of_the_haskell_ecosystem_august_2015/cu5voaq)

**Comment by Gabriella439** [comment]
Fixed by d96134a4a928aa12145c3b7bb0bd62dac54c92e6

**Comment by bitemyapp** [comment]
@Gabriel439 thank ye. You didn't include MVar in the list of numbers, was that intentional? Take/put on an MVar is _ludicrously_ fast, on par with most locking mechanisms.

**Comment by Gabriella439** [comment]
Good idea.  I'll add `MVar` numbers, too

**Comment by bitemyapp** [comment]
@Gabriel439 I have numbers for this, but I'd want to revalidate before putting it in your resource. Do you want me to rebenchmark and report or do you already know what's typical?

Edit: https://github.com/jberryman/chan-benchmarks#some-analysis-of-primitive-operations matches my experience.

**Comment by Gabriella439** [comment]
I'll trust you and @jberryman.  So it looks like the 10-20 ns range, then?

**Comment by bitemyapp** [comment]
@Gabriel439 yeppers. Variance within that range usually attributable to clock speed. (2 ghz laptop vs. 4ghz desktop/server)
