### ISSUE TITLE
Consider adding Postgrest to server-side or DB section

### ISSUE THREAD

**Issue by newswim** [Gabriel439/post-rfc#110]
[Postgrest](https://github.com/begriffs/postgrest) is a service that uses its own stack of popular libraries to generate a REST API that reflects a Postgres schema.

I rarely get to work with Haskell but I am using a GraphQL project ([link](https://www.graphile.org/)) which was _heavily_ inspired by the Postgrest project and it stands out as an extremely useful service for small teams that want to maintain a single source of truth and not worry about optimizing every query by hand.

**Comment by Gabriella439** [comment]
Sorry for the delay.  How about mentioning `postgrest` in the "Server-side programming" section underneath a new subsection for useful server-tools written in Haskell?

**Comment by Gabriel439** [comment]
Sorry for the delay.  How about mentioning `postgrest` in the "Server-side programming" section underneath a new subsection for useful server-tools written in Haskell?

**Comment by Gabriella439** [comment]
Fixed by 281dae5d2d578eb33162700dc843fac97d876633

**Comment by newswim** [comment]
Cool! Thanks Gabe :)

**Comment by Gabriella439** [comment]
You're welcome! :)
