### ISSUE TITLE
Education Resources lacks intermediate or advanced material

### ISSUE THREAD

**Issue by JulianLeviston** [Gabriel439/post-rfc#128]
While it's obvious to focus on beginners in this section, the intermediate and advanced material is somewhat lacking. There are numerous papers that are useful in this regard, and it'd be great if there was some guidance on discovering papers, blog posts and other more advanced material too (like... start with these papers, then look in their reference sections and bibliographies for more papers, use the topics you discover as search terms to find more papers like this, blog entries on it, etc).

As first example, I'd consider Yorgey's monoid paper as basically indispensible reading for anyone who wishes to gain a deep first step into a topic which underpins much of computation (let alone only computation in Haskell).

This is something almost exclusively available to Haskell... we have a plethora of academic resources available to us, and we're almost the default language for exploring many topics at the connection point between mathematics and computation.

As with many things in Haskell, while learning the basics of a topic under question is good, useful, and at times reasonably tricky in itself, a mere discussion of how it's implemented, what it is on a face value and a couple of examples is not where the most interesting regions, or even the meat of the difficulty of the topic often lies — usually it lies in an exploration of the ramifications of the choices made in whatever packages is under discussion — that is, in using it across many varied contexts.

I firmly believe this is the reason Monads have been traditionally difficult to understand, aside from the nomenclature issue of Haskell that seems to go largely unnoticed (that is, when it comes to typeclasses, we use the same words for a value of a type as for a type as for a typeclass as for its instances: point in case the answer to the quesiton "what is monad?" Maybe is an example of a monad, Just 5 is an example of a monad, Monad typeclass is monad, and the monad instances for each type are how a monad is defined — this is inherently confusing).

That's to say, the core reason pieces of Haskell are difficult to undersatnd is that they're often extremely abstract, and in teaching it, often the ramifications are skipped over, which is where the subtleties, practical value and interesting parts of the topic usually reside.

BTW, love how the SOTU is taking shape!

**Comment by nponeccop** [comment]
Regarding advanced topics:

- At some point (I think at the early 2000s) there were dozens of books on object oriented modeling and design. There are no books on design of large-scale functional programs.
- We need an extended version of Typeclassopedia
- We need a kmettopedia as well (and mcbridopedia, gonzalespedia and snoymanpedia to less extent)

In general, we still need a high level overview of Stackage, I think there are some 100 essential packages, and they are not always easy to find (the great regexps of `text-icu` are a notorious example).

**Comment by Gabriella439** [comment]
Note that the main purpose of this document is mainly for people new to Haskell to assess its suitability for an upcoming project they are contemplating

I do think there should be a collection of educational resources spanning multiple skill levels, but I'm not sure if this document is the best place to organize that information

**Comment by JulianLeviston** [comment]
That's fair enough, but that's not what the introduction says that it's for... maybe we might need to amend it?

> In this post I will describe the current state of the Haskell ecosystem to the best of my knowledge and its suitability for various programming domains and tasks. The purpose of this post is to discuss both the good and the bad by advertising where Haskell shines while highlighting where I believe there is room for improvement.

**Comment by Gabriella439** [comment]
I think the introduction is accurate:

> suitability for various programming domains and tasks

> advertising where Haskell shines while highlighting where I believe there is room for improvement

**Comment by nponeccop** [comment]
> I'm not sure if this document is the best place to organize that information

I think #129 and noob-friendly installation instruction in general are out of scope too.

**Comment by Gabriella439** [comment]
Yeah, that's a good point.  On more reflection there probably shouldn't be that level of detail for setting up Windows

**Comment by JulianLeviston** [comment]
> Note that the main purpose of this document is mainly for people new to Haskell to assess its suitability for an upcoming project they are contemplating

I don't think this is mentioned anywhere in the document. That's okay, though :) I'll close this.
