### ISSUE TITLE
Add 'streaming' to the Stream programming section

### ISSUE THREAD

**Issue by adrian-gierakowski** [Gabriel439/post-rfc#132]
https://hackage.haskell.org/package/streaming
https://github.com/haskell-streaming

Tutorials mentioning streaming along pipes and conduit:
https://www.tweag.io/posts/2017-07-27-streaming-programs.html
https://www.tweag.io/posts/2017-10-05-streaming2.html
https://www.tweag.io/posts/2017-11-01-streaming-and-foldl.html

**Comment by Gabriella439** [comment]
Yeah, I think `streaming` is a great library (I'm a little biased, though, since it's inspired by `pipes-group`)

Would you like to submit a pull request to add it?  If not, I can get to this soon, too

**Comment by adrian-gierakowski** [comment]
@Gabriel439 thank you for taking care of this and apologies for not submitting a PR but I had a busy week at work and at home :)

**Comment by Gabriella439** [comment]
You're welcome!  No problem :)
