### ISSUE TITLE
Table of ratings

### ISSUE THREAD

**Issue by jerbaroo** [Gabriel439/post-rfc#138]
I think a concise format of (domain or programming need) showing rating (colour coded for easy visual recognition) would be a very efficient source of information for readers, and highlight the overall current state of the Haskell ecosystem. This could be implemented by just by a coloured rating for each item in the table of contents.

**Comment by Gabriella439** [comment]
Yeah, I agree.  If you can show me a rough sketch of the markdown you had in mind for this table to show this then I can extend it to cover each section

**Comment by ad-si** [comment]
How about something like this:

```
🏆 Compilers 
🥈 Server-side web programming 
🥈 Scripting / Command-line applications
🌱 Data science
```

**Comment by Gabriella439** [comment]
I like it!  I created a pull request: https://github.com/Gabriel439/post-rfc/pull/139
