### ISSUE TITLE
Mention massiv in data structures section

### ISSUE THREAD

**Issue by sjakobi** [Gabriel439/post-rfc#158]
http://hackage.haskell.org/package/massiv

I'm not sure if it's ready to be used in anger though. I haven't actually used it myself. Thoughts @lehins?

**Comment by Gabriella439** [comment]
@sjakobi: I think we should include it, judging mainly by the quality of the documentation and also this overview of how it compares to other libraries:

https://github.com/lehins/massiv/blob/master/README.md#other-libraries

**Comment by sjakobi** [comment]
I just saw that it's already mentioned in the numerical programming section: https://github.com/Gabriel439/post-rfc/blob/master/sotu.md#numerical-programming

I'll make a PR.

**Comment by lehins** [comment]
@sjakobi and @Gabriel439 thank you for including `massiv` in the list. I do hope it will get used in anger ;) I am continuously improving the library and will continue maintaining it indefinitely, just because it's one of my favorite topics and I really enjoy working on it.
