### ISSUE TITLE
hindent unmaintained

### ISSUE THREAD

**Issue by louwers** [Gabriel439/post-rfc#176]
https://github.com/chrisdone/hindent/issues/557

**Comment by nponeccop** [comment]
It should probably be replaced by brittany - it's maintained and supported by haskell-ide-engine:

https://github.com/lspitzner/brittany/commits/master

**Comment by louwers** [comment]
> It should probably be replaced by brittany - it's maintained and supported by haskell-ide-engine:
> 
> https://github.com/lspitzner/brittany/commits/master

Looks good! Can you create a PR?

**Comment by mihaimaruseac** [comment]
`hindent` will have a new maintainer and will be maintained again

**Comment by anacrolix** [comment]
Is there any update on the status of hindent?

**Comment by mihaimaruseac** [comment]
It is maintained now, has had a new release.
