### ISSUE TITLE
What would you need to classify haskell as "best in class" for Testing?

### ISSUE THREAD

**Issue by NorfairKing** [Gabriel439/post-rfc#184]

**Comment by Gabriella439** [comment]
@NorfairKing: I think basically when we can confidently claim that Haskell is superior to Python in every way for testing.  The impression I get is that people widely view Python as the leading language for test automation, so you'd have to dethrone Python.

**Comment by silky** [comment]
As a random programmer in both ecosystems I'd be confident to make that claim!

**Comment by NorfairKing** [comment]
@Gabriel439 That sounds fair! As far as I can tell, Haskell beats python in every way for testing.
However, I'm not a great python dev so I would need someone who is to show me how python is better at testing.

With the addition of [Validity-based testing](https://github.com/NorfairKing/validity) together with [`sydtest`](https://github.com/NorfairKing/sydtest), I claim that Haskell now deserves a "best in class" rating for testing.

**Comment by Gabriella439** [comment]
@NorfairKing: Alright, if you'd like to submit the PR with the updated rating and description justifying the rating then I'd accept changing the status to best in class

**Comment by NorfairKing** [comment]
@Gabriel439 Coming up! But please don't do it just because I asked, if you disagree.
If you disagree then I have more work to do, but I'm happy to do it :)

**Comment by Gabriella439** [comment]
@NorfairKing: I'm not sure, but my view is that the easiest way to find out is to just make the bold claim and see if people push back on it or not.  The worst that happens is that we can always walk things back if others disagree
