### ISSUE TITLE
No mention of learning resources

### ISSUE THREAD

**Issue by GetContented** [Gabriel439/post-rfc#24]
Lack of great beginner resources is one of the most fundamental problems in Haskell to date IMO.

I'm aware there are major efforts being made in improving the situation, (for example http://haskellbook.com), but the fact that this is left out of your state of the ecosystem document kind of speaks volumes about how unimportant this is deemed by most Haskellers.

For a language which has had as much influence on the programming community and understanding what it is we do as programmers as Haskell has, I think we could afford to be better at explanation.

When learning and programming Haskell you almost have no choice but to be aware of what you're doing when you're doing it. This is so different than any other language, and I feel that it's actually the source of why it's so difficult to learn Haskell for people: you're not just learning a language, you're learning how to adjust and change your thinking as well. You're learning what you're doing as well as how to be able to do it.

So if you could consider putting an educational resources section in, that'd be very pleasant :)

**Comment by GetContented** [comment]
I think this has been achieved by inlining educational resources in each section. It'd be quite useful to have a "general books" section, but I'll close this and open a different issue as per your instructions on suggesting books.

**Comment by Gabriella439** [comment]
Although you've closed the issue I just want to say that I agree.  Learning material is not that great for newcomers, especially in the book department
