### ISSUE TITLE
Textbooks to add

### ISSUE THREAD

**Issue by GetContented** [Gabriel439/post-rfc#38]
The following are pretty not too bad:
- Thinking Functionally with Haskell - Richard Bird
- Programming in Haskell - Graham Hutton
- The revised report - Simon Peyton Jones, et al (while not a textbook, it's obviously incredibly valuable from a pedagogical perspective)
-  Parallel and Concurrent Programming in Haskell - Simon Marlow

However, they're all quite a bit outdated, and the newer books seem to not written by people with less than 10 years programming experience. Real World Haskell is also quite good but is quite long in the tooth.

I don't know if I'd class the textbook situation best in class by any means. I think perhaps that it's fair to say that the textbook situation in Haskell is severely lacking in updated or good beginner material.

Most of the textbooks I've seen are stupendously dry, with the exception of the LYAH style textbooks which is kind of silly and at times irritatingly distracting, and potentially quite confusing.

**Comment by Gabriella439** [comment]
So the only thing that I've left out was "Programming in Haskell", mainly because I was concerned that it was a bit too academic

**Comment by GetContented** [comment]
Interesting. I didn't find it to be such.

Is this article primarily for beginners? There's no judgement here on my part, just interest.

Also, I'd probably recommend SICP, even though it's written in Scheme, it's so comprehensive... while perhaps it's too math driven if you're concerned about academia. Personally, though, I don't see how it's possible to be a programmer if you're not prepared to learn at least SOME math.

(One REALLY useful section from SICP for the Haskeller - especially the beginning Haskeller from an imperative language - is section 3.5, I think it is, which is a section on lazy evaluation, thunks and streams.) https://mitpress.mit.edu/sicp/full-text/book/book-Z-H-4.html#%_toc_start

The really cool thing about SICP is that the authors are specific about what they're doing when they're doing it, so you get a deep understanding of evaluation order, strictness, purity, imperative or declarative style, pass by value or pass by reference, etc. When they explain stuff they explain their context at all (just like a schemer would, because every expression only really has value in a context (or an environment, in scheme/LISP terms)... this way of thinking can be very valuable and useful, because it's quite complete.

**Comment by Gabriella439** [comment]
I like a mathematical approach to programming (much more than most people), which is why I still included Richard Bird's book.  However, I'm really searching for books that are marketed towards the "blue collar" programming crowd because that's a weak point in Haskell's bookshelf.

**Comment by GetContented** [comment]
Ah... people who just want to get stuff done.

I think it's a weak point by design of Haskell isn't it? Haskell is for people who want to understand what they're doing and get stuff done, too, no?
