### ISSUE TITLE
Shouldn't "Better, faster binary serialization" be also added to "Serialization"?

### ISSUE THREAD

**Issue by qrilka** [Gabriel439/post-rfc#45]
As a followup to Faster binary serialization?
I'm referring to https://github.com/meiersi/HaskellerZ/blob/master/meetups/20150529-ZuriHac2015_Duncan_Coutts-Better_Faster_Binary_Serialization/binary.pdf

**Comment by Gabriella439** [comment]
So there is a link in there to a similar set of slides.  Are these slides more comprehensive?

**Comment by qrilka** [comment]
They have much in common but the new ones seems to be more focused on deserialization.
I think it makes sense to have both links
