### ISSUE TITLE
Add 'Spock' to server-side programming libraries

### ISSUE THREAD

**Issue by agrafix** [Gabriel439/post-rfc#47]
I'd argue that [Spock](http://hackage.haskell.org/package/Spock) deserves a Spot in the server-side programming libraries, too. It fits well between the "gap" between scotty and the yesod group as it is still pretty simple but provides most features for medium sized applications. It's commercially used in production for over a year now by different companies. What do you think?

**Comment by Gabriella439** [comment]
I agree.  #46 will add this and it just needs to fix a typo before I merge it

**Comment by agrafix** [comment]
Great :-)

**Comment by Gabriella439** [comment]
Fixed by #46
