### ISSUE TITLE
ad - automatic differentiation

### ISSUE THREAD

**Issue by aaronlevin** [Gabriel439/post-rfc#5]
This has always stood out as an interesting and uniquely-haskell library. I'm not sure where it should go.

I'd be happy to submit a PR with a suggestion of a good category. Data science?

https://hackage.haskell.org/package/ad

**Comment by ocharles** [comment]
`ad` is generally useful in the machine learning field (though I also used it recently to do some root-finding I needed for graphics animations. It probably belongs in either machine learning or just numerics.
