### ISSUE TITLE
Check out `gtk3`

### ISSUE THREAD

**Issue by Gabriella439** [Gabriel439/post-rfc#50]
Charles Durham ([@ratzes](https://twitter.com/ratzes)) reported that the `gtk3` package was more mature and easier to use than `gtk`.  This is just a reminder to myself to check it out more deeply when I have time

**Comment by juhp** [comment]
gtk3 obsoleted gtk2 years ago: it took Haskell ages to catch up. All new Haskell apps should definitely use `gtk3` not `gtk`. :)

**Comment by unhammer** [comment]
There is also https://github.com/haskell-gi/haskell-gi (as featured in https://lettier.github.io/posts/2016-08-15-making-movie-monad.html )

**Comment by nponeccop** [comment]
GTK and GTK3 are both deprecated by haskell-gi, see #123

**Comment by Gabriella439** [comment]
I'll go ahead and close this, then.  #123 fixes this issue
