### ISSUE TITLE
Front-end web programming: mention templating

### ISSUE THREAD

**Issue by killerswan** [Gabriel439/post-rfc#56]
Another area for improvement, IMHO:
- Haskell tools tend to focus on building HTML pages _without writing HTML_.  That's cool, but not appropriate for everyone.  Projects to watch: [Hastache](https://github.com/lymar/hastache) for Mustache templates (fairly mature), and @sourrust's [Karver](https://github.com/sourrust/karver) (inspired by Jinja) which finally provides some whole-page HTML templating.

**Comment by Gabriella439** [comment]
Yeah, I will definitely add `Hastache` / `Karver`.  I also want to mention `lucid` if you haven't checked it out already (it's an in-language DSL for building HTML).
