### ISSUE TITLE
Databases: RDF / Triplestores

### ISSUE THREAD

**Issue by GetContented** [Gabriel439/post-rfc#57]
Just wondering if you'd consider mentioning something about Haskell support for these database types.

**Comment by Gabriella439** [comment]
I don't know anything about RDF or Triplestores.  Do you have any material I should read to learn more?

**Comment by GetContented** [comment]
Mostly I'm interested in the "state of the union" on non-SQL (ie graph) databases and connectivity to these DBs from Haskell. I also don't know much about this area. It just seems that SQL is quite represented, but other database types aren't.

**Comment by GetContented** [comment]
If you don't know much about this, chances are there won't be much interest in it, so I'll close this for now.
