### ISSUE TITLE
Mention the `megaparsec` library under Parsers

### ISSUE THREAD

**Issue by Gabriella439** [Gabriel439/post-rfc#59]
Possibly replace `parsec`?

**Comment by mrkkrp** [comment]
It would be good if we could just mention it in “Parsing / Pretty-printing” section. I could prepare a PR if you don't mind. Although I honestly don't see how Parsec can be preferred to Megaparsec now, the library is kinda “famous” and cannot be just replaced (at least not without explanation).

**Comment by Gabriella439** [comment]
Yes, please prepare a pull request, but still keep `parsec` in the list.  My main reservation about `megaparsec` is that I hit a non-termination bug the last time I used the library so I'm hesitant to recommend it completely over `parsec`.

**Comment by mrkkrp** [comment]
Can you describe how to reproduce that bug? Can you open an issue?

**Comment by Gabriella439** [comment]
Unfortunately, I don't have the reproducing code any longer.  It was a while ago

**Comment by mrkkrp** [comment]
I know of at least one case when people switched from Parsec to Megaparsec in commercial environment and feedback was very positive. It's sad that you don't have reproducing code :-(

**Comment by Gabriella439** [comment]
I think it's fine if the pull request says something like "`megaparsec` is a modern and improved version of `parsec`" but still keep the reference to `parsec` just so that if people have any issues they know that they can fall back on `parsec`.
