### ISSUE TITLE
Type-Driven Development Section

### ISSUE THREAD

**Issue by GetContented** [Gabriel439/post-rfc#80]
This section has quite a few issues. One in particular stands out, which is this:

> The biggest advantage of types is that they can prove the complete absence of programming errors for all possible cases, whereas tests cannot examine every possibility

This is not true. Perhaps one could modify it to say that types can prove the complete absence of type errors, but "programming errors" implies logical errors, too, which type checking can't detect. (IMHO).

**Comment by Gabriella439** [comment]
Yeah, I should clarify by saying something like "absence of programming errors that you can encode in the type system"

**Comment by GetContented** [comment]
how about "prove the complete absense of runtime type errors for all possible cases, whereas tests cannot examine every possibility" ?
