### ISSUE TITLE
Machine Learning libraries

### ISSUE THREAD

**Issue by brezal** [Gabriel439/post-rfc#96]
This library wasn't inlcuded in the machine learning section: https://github.com/tensorflow/haskell

**Comment by brezal** [comment]
Also, https://hackage.haskell.org/package/hslibsvm and https://hackage.haskell.org/package/HSvm (these haven't been updated since 2009) were mentioned in this stackoverflow question: https://stackoverflow.com/questions/2268885/machine-learning-in-ocaml-or-haskell

**Comment by Gabriella439** [comment]
@brezal: Have you used any of these libraries before?  The main reason that I'm asking is that I would like for at least one person to vouch for a library before including it in the list (and I've never used any of these myself)

**Comment by silky** [comment]
i've used tensorflow haskell

it's got potential, but it's immature at the moment in my opinion. compared to the python api, there is a fair chunk of functionality that is missing.

in a few months it should be much improved.

**Comment by brezal** [comment]
@Gabriel439 I haven't used these libraries yet. There is also https://github.com/HuwCampbell/grenade which was referenced in http://www.stephendiehl.com/posts/haskell_2017.html 

Thanks for the information. I'll close the issue and reopen if there are updates regarding any of these libraries.
