### ISSUE TITLE
Add a subsection on code formatting tools like hindent and stylish-haskell

### ISSUE THREAD

**Issue by sjakobi** [Gabriel439/post-rfc#99]
I think automatic code formatting is a "common programming need", so I think it deserves its own subsection.

For the rating, I'd say it's currently immature at best – stylish-haskellish AFAIK doesn't reformat code blocks apart from alignment, hindent is buggy and has questionable style choices.

**Comment by Gabriella439** [comment]
So I conducted an informal twitter poll about `hindent` here:

https://twitter.com/GabrielG439/status/823252348508073984

... and the consensus seems to be that it is okay, so I might end up giving a "Mature" rating and then if I'm wrong I'll let people yell at me and tell me why it's not mature :)

How does that sound?

**Comment by sjakobi** [comment]
Hey, thanks for making that poll!

I disagree with the rating of course – hindent is simply too [buggy](https://github.com/chrisdone/hindent/issues?q=is%3Aissue+is%3Aopen+label%3A%22type%3A+bug%22) at this time.

Still a good plan! Thanks for taking such great care of this document!

**Comment by sjakobi** [comment]
> I disagree with the rating of course – hindent is simply too buggy at this time.

Oh, I think I missed that you define "mature" as "suitable for most programmers". In that sense, it's probably the right label – hindent is useful to format individual code blocks after all. But one cannot use it blindly on entires files with the expectation that the output will be well-formatted and non-broken, which IMO should be the goal for a code formatting tool.

**Comment by sjakobi** [comment]
Thanks, https://github.com/Gabriel439/post-rfc/commit/802de541494d2c406b39324c90a1028a6edb1387 is a good starting point!

**Comment by Gabriella439** [comment]
You're welcome!
